name: first pipeline workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "my first GitHub Actions Job"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: list files
        run: ls -ltra
      
      - name: Read file
        run: cat README.md
